### ISSUE TITLE
Nitpick: "UTF-8"

### ISSUE THREAD

**Issue by meedstrom** [kickingvegas/casual-dired#36]
This is no big deal, but it struck me as a little odd-sounding in the readme. As I understand it, they're Unicode symbols, not UTF-8 symbols.

UTF-8 is a way to encode Unicode, and Unicode is the giant table of codepoints that defines how each one should approximately look (which is then implemented slightly differently by various fonts). The Transient buffer could technically be coded as UTF-16 or UTF-32 (no reason though) and still show the same symbols, given the same font. I think.

**Comment by meedstrom** [comment]
You've got quite a professional process! I've never submitted a PR to myself. Do you feel benefits from doing it that way? Not snarking, just curious if it's something I should do too.

**Comment by kickingvegas** [comment]
@meedstrom As with all things involving computers, “it depends.” I’ve found in writing software that being disciplined about making changes is a net positive. It is largely a gift to your future self or to others who will work with it because invariably you’ll leave that codebase for some period of time, losing track of what you did. Having a good record of changes can help you recover that knowledge. This is especially the case for software you intend to make public. So I make PRs even though I’m the sole maintainer right now. That said, a lot of the mechanics of making a PR I have automated using a `Makefile` and [gh](https://cli.github.com/) which will pre-populate/generate notes from your commit messages. If your commit messages are clean then it is a significant time saver.
